### PR TITLE
TMEDIA-653

### PR DESCRIPTION
**Pull request by ecarlisle**
# Overview
A consistent means of caching `node_modules` with GitHub actions has been verified.

# Steps
1. `.github/workflows/test-dependency-caching.yml` was added to test dependency caching between pushes.
2. The [Caching packages dependencies](https://github.com/actions/setup-node#caching-packages-dependencies) method documented in (/actions/setup-node)[https://github.com/actions/setup-node] readme was attempted. This unfortunately produced vague results. Though cache key reporting was seen in the action output, there was no output indicating that dependencies were not being re-fetched.
3. The (Skipping steps based on cache-hit)[https://github.com/actions/cache#skipping-steps-based-on-cache-hit] documented in the (actions/cache)[https://github.com/actions/cache] readme was tried instead and behaved as anticipated. (Node-specific)[https://github.com/actions/cache/blob/main/examples.md#node---npm] documentation was used for the cache path, cache key naming, and restore key naming, including using `~/.npm` as the caching path.

# Testing:
1. Observe these runs of the Test Dependency Caching action. `npm ci` was only run on the two pushes where repo dependencies changed.
image
2. On pushes where dependencies were not affected, the action output clearly shows cache restoration and that the dependency installation step was skipped.
image
3. Further testing can be made by pushing commits that do and do not change dependencies.

# Note: 
1. Changes in this branch are for testing only and should not be merged with this branch. @ecarlisle will ensure that this pattern is documented for re-use.

### CODE REVIEW

**Comment by matthewroach** [comment]
@ecarlisle - On the commit where you remove a package from the dependencies the Github action ran and used cache instead of reinstall dependencies, that's not correct is it? -> https://github.com/WPMedia/themes-lerna-playground/runs/5011004138?check_suite_focus=true

**Comment by ecarlisle** [comment]
> @ecarlisle - On the commit where you remove a package from the dependencies the Github action ran and used cache instead of reinstall dependencies, that's not correct is it? -> https://github.com/WPMedia/themes-lerna-playground/runs/5011004138?check_suite_focus=true

@matthewroach : For me this raises the question of tying an instance of an action running to the triggering action. In other words, if I didn't mention dependencies in the commit message, how could I verify the behavior?

I'll look into this. cc: @JackHowa

**Comment by JackHowa** [comment]
if the package-lock changes, then the github action should re-run the npm install
https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows#using-contexts-to-create-cache-keys

you can trigger a package-lock change by updating deps or installing or removing ones

**Comment by JackHowa** [comment]
this should be the ac:


can you respond in the pr with the new test criteria and your commits and actions for it: step 1. install new cache. step 2. make an empty commit or no change to the package-lock. see no new install. step 3. update the package-lock. see a new install

similar to what I did: 

 [cache set initially once 1 package added](https://github.com/JackHowa/github-action-cache-test/runs/5041591261?check_suite_focus=true)
https://github.com/JackHowa/github-action-cache-test/runs/5041591261?check_suite_focus=true 
cache used successfully on empty commit, no change to package-lock
https://github.com/JackHowa/github-action-cache-test/runs/5041604263?check_suite_focus=true 
cache not found bc package-lock change, so reinstall
https://github.com/JackHowa/github-action-cache-test/runs/5041624796?check_suite_focus=true



[](https://github.com/actions/cache#outputs)restore-keys - An ordered list of keys to use for restoring the cache if no cache hit occurred for key

weird https://github.com/actions/cache#inputs

**Review by JackHowa — DISMISSED** [review]
Working as expected with a change registered

**Pull request closed without merging**
